### PR TITLE
Add Embed resource to GraphQL.

### PR DESCRIPTION
**Pull request by DFurnes**
This pull request adds an `Embed` type and `embed(url)` query to GraphQL. It supports all types in the [OEmbed](https://oembed.com) spec (for whitelisted domains) & otherwise falls back to Facebook/Twitter metatags.

I'm knocking this out before finishing up the other Phoenix content types for two reasons:
1. This is a big performance outlier in Phoenix's API, since we're "blocked" on however long the embedded page takes to load. By moving this into a serverless environment, we're no longer taking up the single Heroku dyno's limited concurrency.
2. We don't currently have a "clear cache" button for these items in Phoenix, so there's no editor UX regression in extracting them (unlike Contentful entries, which will temporarily require a developer's help to clear cache until we implement Contentful webhooks).

Screen Shot 2019-03-14 at 11 54 05 AM

### CODE REVIEW

**Comment by DFurnes** [comment]
Some examples for various types of embeds we use on Phoenix right now:

```gql
{
  embed(url: $url){
    title
    authorName
    providerName
    thumbnailUrl
    description
    html
  }
}
```

#### a dosomething.org campaign:
```json
{
  "data": {
    "embed": {
      "title": "Breakup Bash",
      "authorName": null,
      "providerName": "DoSomething.org",
      "thumbnailUrl": "https://images.ctfassets.net/81iqaqpfd8fy/2GVKZ1W2TSyAqMm4Se60Gc/dbb994d89a302cc2e7ece73950649293/16270738388_63743abbfa_b.jpg?w=1200&h=1200&fm=jpg&fit=fill",
      "description": null,
      "html": null
    }
  },
}
```

#### a dosomething.org page:
```
{
  "data": {
    "embed": {
      "title": "Explained: The National Emergency",
      "authorName": null,
      "providerName": "DoSomething.org",
      "thumbnailUrl": "https://images.ctfassets.net/81iqaqpfd8fy/52AYz10NxJOt8EjTakS6Yl/9432331ee1784b22998f84b7f2b2202b/border-wall.jpg?w=1200&h=1200&fm=jpg&fit=fill",
      "description": "What’s happening and how it affects us all.",
      "html": null
    }
  },
```

#### an instapage:

```json
{
  "data": {
    "embed": {
      "title": "Register to vote in less than two minutes",
      "authorName": null,
      "providerName": "You can register to vote online... literally right now! It's fast, easy, and requires only basic information like your street address. Let's Do This!",
      "thumbnailUrl": "https://v.fastcdn.co/u/e971e063/34326761-0-34242711-0-8D3A0430.jpg",
      "description": "You can register to vote online... literally right now! It's fast, easy, and requires only basic information like your street address. Let's Do This!",
      "html": null
    }
  },
}
```

#### a buzzfeed article:
```json
{
  "data": {
    "embed": {
      "title": "An Appeals Court Ruled For The First Time That Trump Can Be Sued In State Court",
      "authorName": null,
      "providerName": "BuzzFeed News",
      "thumbnailUrl": "https://img.buzzfeed.com/buzzfeed-static/static/2019-03/14/13/campaign_images/buzzfeed-prod-web-03/an-appeals-court-ruled-for-the-first-time-that-tr-2-15870-1552584215-5_dblbig.jpg",
      "description": "\"Though he is tasked with significant responsibilities, the President is still a person, and he is not above the law.\"",
      "html": null
    }
  },
}
```

#### a youtube video:
```json
{
  "data": {
    "embed": {
      "title": "Marvel Studios' Avengers: Endgame - Official Trailer",
      "authorName": "Marvel Entertainment",
      "providerName": "YouTube",
      "thumbnailUrl": "https://i.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
      "description": null,
      "html": "<iframe width=\"480\" height=\"270\" src=\"https://www.youtube.com/embed/TcMBFSGVi1c?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"
    }
  },
}
```

**Comment by DFurnes** [comment]
Whoops, noticed a mistake I'd made when adding the `idField` parameter to `transformResponse`! Since we sometimes used that as a "direct" [`Array.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) callback, it was getting the index here (like `1`, `2`, …) instead of defaulting to `id`. Fixed in 26d79fe.

**Comment by mendelB** [comment]
(What was the reason for altering the "prefer" config in https://github.com/DoSomething/graphql/pull/78/commits/766fd8611ba802c916852e2a6de0e962dd306927?)

**Comment by DFurnes** [comment]
> (What was the reason for altering the "prefer" config in https://github.com/DoSomething/graphql/pull/78/commits/766fd8611ba802c916852e2a6de0e962dd306927?)

I'd originally used the OEmbed library's middleware to conditionally opt-out of fetching an OEmbed and instead use Twitter/OpenGraph metatags. This sorta worked, but meant that we would have to whitelist anything we wanted to embed, even if just getting "safe" content tags from an article.

I swapped things around in 32d1643 to always fallback to metatags for sites that we don't want "rich" OEmbed responses from, but had forgotten to remove the old config from the previous behavior.

**Pull request merged**
