### PR TITLE
De-duplicate calls to Airtable API to fetch data

### PR DESCRIPTION
**Pull request by aaronschachter**
### What's this PR do?

This pull request is part 2 of aiming to avoid making multiple API requests to Airtable when the cache is stale, per [Slack thread](https://dosomething.slack.com/archives/CUQMU4Q6B/p1600803607030600?thread_ts=1600365197.008800&cid=CUQMU4Q6B).

### How should this be reviewed?

👀 

### Any background context you want to provide?

I've been manually testing by inspecting the server logs and manually making GraphQL requests in the GraphQL playground, but should test it better by polling the query with a script. Aim to look into working on that tomorrow.

### Relevant tickets

References [Pivotal #174934325](https://www.pivotaltracker.com/story/show/174934325).

### Checklist

- [ ] This PR has been added to the relevant Pivotal card.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Review by DFurnes — APPROVED** [review]
Looks good to me! I wonder if this "one promise at a time" logic might be nice to extract into a helper (and if so what we'd name it...). Could be a nice cleanup sprint ticket if you're down!

**Comment by aaronschachter** [comment]
I dig the idea of extracting into a helper... seems a little tricky. I'd think the helper would need a `promise` variable set for each request we'd want to "rate limit"?  Or maybe having different `cache` classes is an idea that came to mind when I was working on #278 -- where one class could use the standard `expiresIn` and the `generateFunc` class would have this logic built-in.

**Comment by aaronschachter** [comment]
Testing locally by adding this script into the Gambit codebase, and looks like this fix should do the trick -- not running into any of the `forEach` errors. 

```
// Load environment vars.
require('dotenv').config();

const graphql = require('./lib/graphql');

const main = async () => {
  try {
    for (let i = 0; i < 10000000000000000; i++) {
      const data = await graphql.fetchVotingInformationByLocation('US-NJ');

      console.log(data);    
    }
  } catch (error) {
    console.log(error);
  }

};

main();
```

**Comment by DFurnes** [comment]
> I dig the idea of extracting into a helper... seems a little tricky. I'd think the helper would need a `promise` variable set for each request we'd want to "rate limit"? Or maybe having different `cache` classes is an idea that came to mind when I was working on #278 -- where one class could use the standard `expiresIn` and the `generateFunc` class would have this logic built-in.

Yeah, it's definitely a little tricky!!

I _think_ we could solve this by using a higher-order function that creates this `let promise` inside a closure and returns the function that provides access to it... each time we call that function we'd create a new "instance" of something we wanted to reuse. Something like this:

```js
function reusePromiseIfPending(callback) {
    let promise = null;

    return function() {
      if (promise) {
        return promise;
      }

      promise = callback().then(data => {
        promise = null;
      
        return data;
     });

     return promise;
  };
```

```
generateFunc: reusePromiseIfPending(fetchVotingInformationRecordsByLocation);
```

**Pull request merged**
